# Generated by Django 5.2.17 on 2026-09-25 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('days', models.DecimalField(decimal_places=2, max_digits=5)),
                ('reason', models.CharField(blank=True, max_length=300)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('supervisor_approved', 'Supervisor approved'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='draft', max_length=25)),
                ('decision_comment', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'ordering': ['-from_date'],
            },
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('annual_entitlement_days', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('accrues_monthly', models.BooleanField(default=True, help_text='Accrue 1/12 of the entitlement each month')),
                ('carry_over_max_days', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('max_balance_days', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_paid', models.BooleanField(default=True)),
                ('requires_evidence', models.BooleanField(default=False)),
                ('appointment_types', models.JSONField(blank=True, default=list, help_text='Empty list means all types')),
                ('term_time_restricted', models.BooleanField(default=False, help_text='Academic staff cannot take during term')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='LeaveLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_date', models.DateField()),
                ('days', models.DecimalField(decimal_places=2, help_text='Positive credit, negative debit', max_digits=6)),
                ('reason', models.CharField(choices=[('accrual', 'Accrual'), ('taken', 'Taken'), ('adjustment', 'Adjustment'), ('carry_over', 'Carry over'), ('forfeit', 'Forfeit'), ('opening', 'Opening balance (migration)')], max_length=20)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['entry_date', 'id'],
            },
        ),
    ]
