# Generated by Django 5.2.17 on 2026-09-29 23:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_initial'),
        ('people', '0002_leave_self_service'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='days_beyond',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Days the balance did not cover (with evidence)', max_digits=5),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='Who the request was sent to on submission. Empty: the campus supervisors', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_to_decide', to='people.employee'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='receipt',
            field=models.JSONField(blank=True, help_text='Issued once, on final approval', null=True),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='evidence_is_medical',
            field=models.BooleanField(default=False, help_text='Evidence is filed as medical: the employee and HR only'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='evidence_name',
            field=models.CharField(default='Supporting document', help_text="What staff are asked for, e.g. Doctor's note", max_length=60),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='over_balance',
            field=models.CharField(choices=[('allow', 'No limit: leave granted at discretion'), ('refuse', 'Refuse a request for more than the balance'), ('evidence', 'Accept more than the balance only with supporting evidence')], default='allow', help_text='Beyond the balance', max_length=10),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='requires_evidence',
            field=models.BooleanField(default=False, help_text='Evidence with every request'),
        ),
        migrations.CreateModel(
            name='LeaveDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(choices=[('manager', 'Manager'), ('hr', 'Human Resources')], max_length=10)),
                ('outcome', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected')], max_length=10)),
                ('actor_name', models.CharField(max_length=160)),
                ('comment', models.CharField(blank=True, max_length=300)),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='leave.leaverequest')),
            ],
            options={
                'ordering': ['decided_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Entitlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('annual_days', models.DecimalField(decimal_places=2, max_digits=5)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entitlements', to='people.contract')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entitlements', to='leave.leavetype')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['contract', 'leave_type'],
                'constraints': [models.UniqueConstraint(fields=('contract', 'leave_type'), name='one_entitlement_per_type'), models.CheckConstraint(condition=models.Q(('annual_days__gte', 0)), name='entitlement_not_negative')],
            },
        ),
    ]
