# Generated by Django 5.2.17 on 2026-10-02 03:07

from django.db import migrations, models


def start_the_clocks(apps, schema_editor):
    """Requests already waiting count from their last change, so the time limits reach them too."""
    LeaveRequest = apps.get_model("leave", "LeaveRequest")
    waiting = LeaveRequest.objects.filter(state__in=("submitted", "supervisor_approved"), waiting_since__isnull=True)
    for request in waiting:
        LeaveRequest.objects.filter(pk=request.pk).update(waiting_since=request.updated_at)


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0004_leave_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='waiting_since',
            field=models.DateTimeField(blank=True, help_text='When it began waiting at its present step: its time limit counts from here', null=True),
        ),
        migrations.RunPython(start_the_clocks, migrations.RunPython.noop),
    ]
