# Generated by Django 5.2.17 on 2026-10-01 22:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0006_remove_next_of_kin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrectionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(choices=[('personal', 'Personal details'), ('contact', 'Contact details'), ('emergency', 'Emergency contacts'), ('dependants', 'Dependants'), ('qualifications', 'Qualifications'), ('previous', 'Work before GSA'), ('bank', 'Bank details'), ('appointment', 'Appointment or contract'), ('leave', 'Leave records'), ('other', 'Something else')], max_length=20)),
                ('wrong', models.TextField(help_text='What is wrong', max_length=1000)),
                ('should_be', models.TextField(help_text='What it should say', max_length=1000)),
                ('state', models.CharField(choices=[('open', 'With Human Resources'), ('corrected', 'Corrected'), ('declined', 'Not changed')], default='open', max_length=12)),
                ('due_by', models.DateField(help_text='When HR should have answered (PRIVACY_RESPONSE_DAYS after asking)')),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True, max_length=1000)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correction_requests', to='people.employee')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrivacyNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(help_text='Plain text; a blank line starts a new paragraph')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, help_text='Empty while it is a draft', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='NoticeAcknowledgement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acknowledgements', to='privacy.privacynotice')),
            ],
            options={
                'ordering': ['-at'],
                'constraints': [models.UniqueConstraint(fields=('notice', 'user'), name='one_acknowledgement_per_notice')],
            },
        ),
    ]
