# Generated by Django 5.2.17 on 2026-10-02 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0010_scan_batches'),
        ('privacy', '0002_retention_and_breaches'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Objection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('part', models.CharField(choices=[('personal', 'Personal details'), ('contact', 'Contact details'), ('emergency', 'Emergency contacts'), ('dependants', 'Dependants'), ('qualifications', 'Qualifications'), ('previous', 'Work before GSA'), ('bank', 'Bank details'), ('appointment', 'Appointment or contract'), ('leave', 'Leave records'), ('other', 'Something else')], max_length=20)),
                ('grounds', models.TextField(help_text="Why, in the person's own situation", max_length=2000)),
                ('state', models.CharField(choices=[('open', 'With the data protection officer'), ('upheld', 'Upheld: that use stops'), ('not_upheld', 'Not upheld')], default='open', max_length=12)),
                ('due_by', models.DateField(help_text='When the officer should have decided (PRIVACY_RESPONSE_DAYS after)')),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('reasons', models.TextField(blank=True, max_length=2000)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objections', to='people.employee')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Restriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('part', models.CharField(choices=[('personal', 'Personal details'), ('contact', 'Contact details'), ('emergency', 'Emergency contacts'), ('dependants', 'Dependants'), ('qualifications', 'Qualifications'), ('previous', 'Work before GSA'), ('bank', 'Bank details'), ('appointment', 'Appointment or contract'), ('leave', 'Leave records'), ('other', 'Something else')], max_length=20)),
                ('ground', models.CharField(choices=[('contested', 'Its accuracy is contested'), ('unlawful', 'Its processing is unlawful'), ('legal_claim', "Kept only for the person's legal claim"), ('objection', 'The person has objected')], max_length=12)),
                ('note', models.TextField(blank=True, max_length=1000)),
                ('lifted_at', models.DateTimeField(blank=True, null=True)),
                ('lifted_reason', models.TextField(blank=True, max_length=1000)),
                ('correction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restrictions', to='privacy.correctionrequest')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restrictions', to='people.employee')),
                ('lifted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('objection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restrictions', to='privacy.objection')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
