# Generated by Django 5.2.17 on 2026-10-10 17:20

import core.fields
import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
import recruitment.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org', '0002_initial'),
        ('people', '0010_scan_batches'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(blank=True, max_length=40)),
                ('state', models.CharField(choices=[('submitted', 'Submitted'), ('shortlisted', 'Shortlisted'), ('interview_scheduled', 'Interview scheduled'), ('interviewed', 'Interviewed'), ('offered', 'Offered'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='submitted', max_length=24)),
                ('previous_state', models.CharField(blank=True, max_length=24)),
                ('decision_comment', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True, help_text='Screening and shortlisting notes')),
                ('reference', models.CharField(default=recruitment.models._new_reference, max_length=20, unique=True)),
                ('check_code', core.fields.EncryptedTextField(blank=True, default=recruitment.models._new_check_code, editable=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationCheckLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('reference', models.CharField(max_length=40)),
                ('matched', models.BooleanField()),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='recruitment.application')),
            ],
            options={
                'ordering': ['-at'],
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('national_id', core.fields.EncryptedTextField(blank=True, editable=True, null=True)),
                ('cv', models.FileField(blank=True, null=True, upload_to=recruitment.models._candidate_file_name)),
                ('cv_original_name', models.CharField(blank=True, help_text='File name as uploaded', max_length=255)),
                ('retention_date', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.AddField(
            model_name='application',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='recruitment.candidate'),
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text="As advertised; defaults to the post's title", max_length=160)),
                ('description', models.TextField(blank=True, help_text='Duties, requirements and how to apply')),
                ('opens_on', models.DateField()),
                ('closes_on', models.DateField()),
                ('state', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vacancies', to='org.position')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'vacancies',
                'ordering': ['-opens_on', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Hire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField(blank=True, help_text='Expected or agreed start date', null=True)),
                ('notes', models.TextField(blank=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='hire', to='recruitment.application')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hires', to='recruitment.candidate')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(blank=True, help_text='Set by onboarding (H-W02) once this hire becomes a staff record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='people.employee')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hires', to='recruitment.vacancy')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='application',
            name='vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='recruitment.vacancy'),
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('location', models.CharField(blank=True, help_text='A room, or a link supplied by GSA; no video service is wired up', max_length=255)),
                ('state', models.CharField(choices=[('scheduled', 'Scheduled'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='scheduled', max_length=10)),
                ('ics_uid', models.UUIDField(editable=False, unique=True)),
                ('sequence', models.PositiveSmallIntegerField(default=0)),
                ('invited_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interview', to='recruitment.application')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('interviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recruitment_interviews', to='people.employee')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['starts_at'],
                'constraints': [django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('state', 'scheduled')), expressions=[('interviewer', '='), (recruitment.models.DateTimeRange('starts_at', 'ends_at', django.contrib.postgres.fields.ranges.RangeBoundary(inclusive_lower=True, inclusive_upper=False)), '&&')], name='no_double_booking_per_interviewer'), models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='interview_ends_after_starts')],
            },
        ),
        migrations.AddConstraint(
            model_name='vacancy',
            constraint=models.CheckConstraint(condition=models.Q(('closes_on__gte', models.F('opens_on'))), name='vacancy_closes_after_opens'),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('vacancy', 'candidate')},
        ),
    ]
