# Generated by Django 5.2.17 on 2026-10-02 00:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0006_remove_next_of_kin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LetterTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(help_text='The same in every version', max_length=40)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('kind', models.CharField(choices=[('appointment', 'Appointment'), ('confirmation', 'Confirmation of appointment'), ('job_letter', 'Job letter'), ('transfer', 'Transfer'), ('promotion', 'Promotion'), ('acting', 'Acting appointment'), ('increment', 'Increment'), ('exit', 'Leaving'), ('other', 'Other')], max_length=20)),
                ('name', models.CharField(max_length=120)),
                ('subject', models.CharField(help_text='The heading line; it may hold fields', max_length=200)),
                ('body', models.TextField(help_text='Paragraphs apart by a blank line, fields in double braces')),
                ('asks', models.JSONField(blank=True, default=list, help_text='What is asked when a letter is written')),
                ('addressed', models.BooleanField(default=True, help_text="Starts with the person's name and post; off for to-whom-it-may-concern letters")),
                ('classification', models.CharField(choices=[('internal', 'Internal'), ('confidential', 'Confidential'), ('medical', 'Medical (restricted)')], default='confidential', max_length=20)),
                ('signatory_name', models.CharField(blank=True, max_length=120)),
                ('signatory_title', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', '-version'],
            },
        ),
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(max_length=30, unique=True)),
                ('issued_on', models.DateField()),
                ('values', models.JSONField(help_text='Every field as it went into the letter')),
                ('sha256', models.CharField(help_text='Fingerprint of the PDF as issued', max_length=64)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='letter', to='people.document')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letters', to='people.employee')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='letters', to='letters.lettertemplate')),
            ],
            options={
                'ordering': ['-issued_on', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='lettertemplate',
            constraint=models.UniqueConstraint(fields=('code', 'version'), name='one_letter_template_version'),
        ),
    ]
