# Generated by Django 5.2.17 on 2026-10-02 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0001_initial'),
        ('people', '0007_assignment_confirmed_on_assignment_grade_careerevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='career_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='letters', to='people.careerevent'),
        ),
    ]
