# Generated by Django 5.2.17 on 2026-10-02 04:37

import core.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0002_letter_career_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='check_code',
            field=core.fields.EncryptedTextField(blank=True, editable=True, help_text='Printed on the letter for checking it; none before item 1.47', null=True),
        ),
        migrations.CreateModel(
            name='LetterCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('reference', models.CharField(max_length=40)),
                ('matched', models.BooleanField()),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('letter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='letters.letter')),
            ],
            options={
                'ordering': ['-at'],
            },
        ),
    ]
