# Generated by Django 5.2.17 on 2026-09-25 15:34

import core.fields
import django.contrib.postgres.constraints
import django.contrib.postgres.operations
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
import people.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        django.contrib.postgres.operations.BtreeGistExtension(),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment_type', models.CharField(choices=[('permanent', 'Permanent'), ('contract', 'Contract'), ('temporary', 'Temporary'), ('sessional', 'Sessional lecturer or instructor'), ('seasonal', 'Seasonal farm or estate worker')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('probation_end', models.DateField(blank=True, null=True)),
                ('is_acting', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('ended', 'Ended')], default='active', max_length=10)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='org.position')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doc_type', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=160)),
                ('file', models.FileField(upload_to='employees/%Y/%m/')),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('classification', models.CharField(choices=[('internal', 'Internal'), ('confidential', 'Confidential'), ('medical', 'Medical (restricted)')], default='internal', max_length=20)),
                ('retention_date', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract_type', models.CharField(choices=[('fixed_term', 'Fixed term'), ('open_ended', 'Open ended'), ('sessional', 'Sessional')], max_length=20)),
                ('term_months', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('signed_on', models.DateField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='people.assignment')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.document')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_no', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('other_names', models.CharField(blank=True, max_length=120)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('X', 'Other or not stated')], default='X', max_length=1)),
                ('national_id', core.fields.EncryptedTextField(blank=True, editable=True, null=True)),
                ('nis_no', core.fields.EncryptedTextField(blank=True, editable=True, null=True)),
                ('tin', core.fields.EncryptedTextField(blank=True, editable=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('next_of_kin_name', models.CharField(blank=True, max_length=120)),
                ('next_of_kin_phone', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(choices=[('active', 'Active'), ('on_leave', 'On leave'), ('suspended', 'Suspended'), ('separated', 'Separated')], default='active', max_length=20)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='org.campus')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='people.employee'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='people.employee'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['last_name', 'first_name'], name='people_empl_last_na_fce3c2_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['campus', 'status'], name='people_empl_campus__44496a_idx'),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('is_acting', False)), expressions=[('position', '='), (people.models.DateRange('start_date', 'end_date', django.contrib.postgres.fields.ranges.RangeBoundary(inclusive_lower=True, inclusive_upper=True)), '&&')], name='one_substantive_holder_per_position'),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='assignment_end_after_start'),
        ),
    ]
