# Generated by Django 5.2.17 on 2026-09-29 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': [models.OrderBy(models.F('signed_on'), descending=True, nulls_last=True), '-id']},
        ),
        migrations.AddField(
            model_name='contract',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='GYD per hour. Leave empty for salaried staff: the rate is then worked out from the grade', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='hours_per_week',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='notice_period_days',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='other_terms',
            field=models.TextField(blank=True, help_text='Allowances, duties or conditions particular to it'),
        ),
    ]
