# Generated by Django 5.2.17 on 2026-10-01 18:07

import core.uploads
from django.db import migrations, models


def keep_existing_names(apps, schema_editor):
    """Files stored before this change keep their stored name as the name they download under."""
    Document = apps.get_model("people", "Document")
    for document in Document.objects.filter(original_name="").only("id", "file"):
        document.original_name = (document.file.name or "").rsplit("/", 1)[-1][:255]
        document.save(update_fields=["original_name"])


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_leave_self_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='original_name',
            field=models.CharField(blank=True, help_text='File name as uploaded', max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to=core.uploads.stored_name),
        ),
        migrations.RunPython(keep_existing_names, migrations.RunPython.noop),
    ]
