# Generated by Django 5.2.17 on 2026-10-01 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_next_of_kin_to_contacts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='next_of_kin_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='next_of_kin_phone',
        ),
    ]
