# Generated by Django 5.2.17 on 2026-10-02 01:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0002_initial'),
        ('people', '0006_remove_next_of_kin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='confirmed_on',
            field=models.DateField(blank=True, help_text='Confirmed in the post after probation', null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='org.grade'),
        ),
        migrations.CreateModel(
            name='CareerEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('transfer', 'Transfer'), ('promotion', 'Promotion'), ('increment', 'Increment'), ('acting', 'Acting appointment'), ('confirmation', 'Confirmation in the post')], max_length=20)),
                ('state', models.CharField(choices=[('scheduled', 'Scheduled'), ('applied', 'In effect'), ('cancelled', 'Cancelled'), ('blocked', 'Held up')], default='scheduled', max_length=10)),
                ('effective_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='When an acting appointment ends', null=True)),
                ('reason', models.CharField(max_length=300)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('problem', models.CharField(blank=True, help_text='Why a scheduled change could not take effect', max_length=300)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_events', to='people.employee')),
                ('from_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='people.assignment')),
                ('from_grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='org.grade')),
                ('to_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='people.assignment')),
                ('to_grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='org.grade')),
                ('to_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='org.position')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-effective_date', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('effective_date')), _connector='OR'), name='career_event_end_after_start')],
            },
        ),
    ]
