# Generated by Django 5.2.17 on 2026-10-02 01:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0007_assignment_confirmed_on_assignment_grade_careerevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Separation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(choices=[('resignation', 'Resignation'), ('retirement', 'Retirement'), ('contract_end', 'End of a fixed-term contract'), ('notice', 'Ended by the School with notice'), ('redundancy', 'Redundancy'), ('dismissal', 'Dismissal for good and sufficient cause'), ('mutual', 'Mutual consent'), ('probation', 'Ended during probation'), ('death', 'Death in service')], max_length=20)),
                ('state', models.CharField(choices=[('leaving', 'Leaving'), ('left', 'Left'), ('withdrawn', 'Withdrawn')], default='leaving', max_length=10)),
                ('notice_given_on', models.DateField(blank=True, help_text='When notice was given, by either side', null=True)),
                ('last_day', models.DateField()),
                ('note', models.CharField(help_text='In words: why, and anything agreed', max_length=300)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('withdrawn_reason', models.CharField(blank=True, max_length=300)),
                ('settlement', models.JSONField(blank=True, help_text='The figures as they stood when the person left', null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='separations', to='people.employee')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_day', '-id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('state', 'leaving')), fields=('employee',), name='one_leaving_at_a_time'), models.CheckConstraint(condition=models.Q(('notice_given_on__isnull', True), ('notice_given_on__lte', models.F('last_day')), _connector='OR'), name='notice_before_last_day')],
            },
        ),
    ]
