# Generated by Django 5.2.17 on 2026-10-02 02:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0008_separation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClearanceStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=30)),
                ('label', models.CharField(max_length=160)),
                ('who', models.CharField(help_text='Who confirms it', max_length=120)),
                ('state', models.CharField(choices=[('open', 'To do'), ('done', 'Done'), ('not_needed', 'Not needed')], default='open', max_length=12)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('cleared_at', models.DateTimeField(blank=True, null=True)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('cleared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('separation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clearance', to='people.separation')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['separation', 'position'],
                'constraints': [models.UniqueConstraint(fields=('separation', 'code'), name='one_step_of_each_kind')],
            },
        ),
        migrations.CreateModel(
            name='ExitInterview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('held_on', models.DateField()),
                ('declined', models.BooleanField(default=False, help_text='Offered, and declined')),
                ('main_reason', models.CharField(blank=True, choices=[('pay', 'Pay and benefits'), ('growth', 'Training and promotion'), ('workload', 'Workload'), ('management', 'Supervision and management'), ('conditions', 'Working conditions'), ('moving', 'Moving away'), ('family', 'Personal or family reasons'), ('retirement', 'Retirement'), ('other', 'Something else')], max_length=20)),
                ('would_recommend', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('unsure', 'Not sure')], max_length=10)),
                ('rating_pay', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('rating_supervision', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('rating_training', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('rating_workload', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('rating_conditions', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('keep', models.TextField(blank=True, help_text='What the School should keep')),
                ('change', models.TextField(blank=True, help_text='What the School should change')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('separation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exit_interview', to='people.separation')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('rating_pay__isnull', True), models.Q(('rating_pay__gte', 1), ('rating_pay__lte', 5)), _connector='OR'), models.Q(('rating_supervision__isnull', True), models.Q(('rating_supervision__gte', 1), ('rating_supervision__lte', 5)), _connector='OR'), models.Q(('rating_training__isnull', True), models.Q(('rating_training__gte', 1), ('rating_training__lte', 5)), _connector='OR'), models.Q(('rating_workload__isnull', True), models.Q(('rating_workload__gte', 1), ('rating_workload__lte', 5)), _connector='OR'), models.Q(('rating_conditions__isnull', True), models.Q(('rating_conditions__gte', 1), ('rating_conditions__lte', 5)), _connector='OR')), name='exit_ratings_one_to_five')],
            },
        ),
        migrations.CreateModel(
            name='IssuedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('key', 'Key'), ('tool', 'Tool or equipment'), ('device', 'Computer, phone or other device'), ('uniform', 'Uniform'), ('protective', 'Protective clothing or gear'), ('card', 'Identity or access card'), ('vehicle', 'Vehicle'), ('book', 'Book or manual'), ('other', 'Other')], max_length=20)),
                ('description', models.CharField(max_length=160)),
                ('tag', models.CharField(blank=True, help_text='Serial number or asset tag', max_length=60)),
                ('issued_on', models.DateField()),
                ('returned_on', models.DateField(blank=True, null=True)),
                ('condition', models.CharField(blank=True, choices=[('good', 'In good order'), ('worn', 'Worn with use'), ('damaged', 'Damaged'), ('lost', 'Lost')], max_length=10)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_items', to='people.employee')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': [models.OrderBy(models.F('returned_on'), nulls_first=True), '-issued_on', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('returned_on__isnull', True), ('returned_on__gte', models.F('issued_on')), _connector='OR'), name='item_returned_after_issue')],
            },
        ),
    ]
