# Generated by Django 5.2.17 on 2026-10-02 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0009_clearancestep_exitinterview_issueditem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doc_type', models.CharField(help_text='What the papers are: contract, certificate...', max_length=40)),
                ('classification', models.CharField(choices=[('internal', 'Internal'), ('confidential', 'Confidential'), ('medical', 'Medical (restricted)')], default='confidential', max_length=20)),
                ('note', models.CharField(blank=True, help_text='Such as: personnel files, cabinet 2', max_length=200)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ScanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="The file's name as sent", max_length=255)),
                ('sha256', models.CharField(blank=True, help_text='To notice a file sent twice', max_length=64)),
                ('refused', models.CharField(blank=True, help_text='Why it was not filed', max_length=300)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='people.scanbatch')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_items', to='people.document')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scanned_items', to='people.employee')),
            ],
            options={
                'ordering': ['at', 'id'],
            },
        ),
    ]
