# Generated by Django 5.2.17 on 2026-10-10 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0010_scan_batches'),
        ('recruitment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('onboarding', 'Onboarding'), ('active', 'Active'), ('on_leave', 'On leave'), ('suspended', 'Suspended'), ('separated', 'Separated')], default='active', max_length=20),
        ),
        migrations.CreateModel(
            name='Onboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('in_progress', 'In progress'), ('documents_submitted', 'Documents submitted, awaiting HR'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='in_progress', max_length=20)),
                ('previous_state', models.CharField(blank=True, max_length=20)),
                ('decision_comment', models.TextField(blank=True)),
                ('waiting_since', models.DateTimeField(blank=True, null=True)),
                ('started_on', models.DateField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, help_text='Why, for a cancelled onboarding', max_length=300)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='onboarding', to='people.employee')),
                ('hire', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='onboarding', to='recruitment.hire')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_on', '-id'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=30)),
                ('label', models.CharField(max_length=160)),
                ('who', models.CharField(help_text='Who confirms it', max_length=120)),
                ('state', models.CharField(choices=[('open', 'To do'), ('done', 'Done'), ('not_needed', 'Not needed')], default='open', max_length=12)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('cleared_at', models.DateTimeField(blank=True, null=True)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('cleared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('onboarding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='people.onboarding')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['onboarding', 'position'],
            },
        ),
        migrations.AddConstraint(
            model_name='onboarding',
            constraint=models.UniqueConstraint(condition=models.Q(('state__in', ['in_progress', 'documents_submitted'])), fields=('employee',), name='one_onboarding_in_progress'),
        ),
        migrations.AddConstraint(
            model_name='onboardingstep',
            constraint=models.UniqueConstraint(fields=('onboarding', 'code'), name='one_onboarding_step_of_each_kind'),
        ),
    ]
