# Generated by Django 5.2.17 on 2026-09-29 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingrecord',
            name='external_ref',
            field=models.CharField(blank=True, help_text='Set when reported by the LMS', max_length=120, null=True, unique=True),
        ),
    ]
