# Generated by Django 5.2.17 on 2026-10-06 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0002_initial'),
        ('training', '0002_trainingrecord_external_ref'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_code', models.CharField(blank=True, help_text="The course's code in the LMS, when it has one", max_length=40)),
                ('title', models.CharField(help_text='The course as staff know it', max_length=160)),
                ('post_title', models.CharField(blank=True, help_text='Staff holding a post with this title (any unit), compared without regard to case', max_length=120)),
                ('due_days', models.PositiveSmallIntegerField(default=30, help_text='Days from assignment to the due date')),
                ('renewal_months', models.PositiveSmallIntegerField(blank=True, help_text='Taken again this often; empty means once', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='training_requirements', to='org.campus')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('org_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='training_requirements', to='org.orgunit')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title', 'id'],
            },
        ),
    ]
