# Generated by Django 5.2.17 on 2026-10-10 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_initial'),
        ('leave', '0005_leaverequest_waiting_since'),
        ('people', '0010_scan_batches'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('effective_from', models.DateField()),
            ],
            options={
                'ordering': ['employee', '-effective_from'],
            },
        ),
        migrations.AlterModelOptions(
            name='shiftpattern',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='leave_request',
            field=models.ForeignKey(blank=True, help_text='The approved leave request covering this day, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_days', to='leave.leaverequest'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='note',
            field=models.CharField(blank=True, help_text="Why it reads as it does, or HR's note", max_length=300),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='resolved',
            field=models.BooleanField(default=False, help_text='HR has looked at this exception'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='scheduled_in',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='scheduled_out',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('late', 'Late'), ('absent', 'Absent'), ('on_leave', 'On approved leave'), ('holiday', 'Public holiday'), ('not_scheduled', 'Not a working day'), ('missing_checkout', 'Checked in, not checked out'), ('corrected', 'Corrected by Human Resources')], default='present', max_length=20),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='source',
            field=models.CharField(choices=[('self', 'Self-service check-in'), ('manual', 'HR correction'), ('import', 'Spreadsheet or crew register import'), ('device', 'Kiosk or biometric device'), ('system', 'Marked automatically (no check-in recorded)')], default='self', max_length=10),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['date', 'status'], name='attendance__date_64c311_idx'),
        ),
        migrations.AddField(
            model_name='employeeshift',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeeshift',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_history', to='people.employee'),
        ),
        migrations.AddField(
            model_name='employeeshift',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='attendance.shiftpattern'),
        ),
        migrations.AddField(
            model_name='employeeshift',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='employeeshift',
            constraint=models.UniqueConstraint(fields=('employee', 'effective_from'), name='one_shift_change_per_day'),
        ),
    ]
