# Generated by Django 5.2.17 on 2026-10-02 04:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org', '0002_initial'),
        ('people', '0009_clearancestep_exitinterview_issueditem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(max_length=20, unique=True)),
                ('kind', models.CharField(choices=[('accident', 'Accident'), ('near_miss', 'Near miss'), ('dangerous', 'Dangerous occurrence'), ('disease', 'Occupational disease')], max_length=12)),
                ('occurred_at', models.DateTimeField(help_text='When it happened; for a disease, when it was first suspected')),
                ('place', models.CharField(help_text='Exactly where, such as the feed mill or pen 3', max_length=120)),
                ('industrial', models.BooleanField(default=False, help_text='At an industrial establishment, such as the processing unit or a workshop')),
                ('description', models.TextField(help_text='What happened')),
                ('immediate_action', models.TextField(blank=True, help_text='What was done at once')),
                ('state', models.CharField(choices=[('reported', 'Reported'), ('investigating', 'Being looked into'), ('closed', 'Closed')], default='reported', max_length=14)),
                ('cause', models.TextField(blank=True, help_text='What the investigation found: why it happened')),
                ('investigated_on', models.DateField(blank=True, null=True)),
                ('closed_on', models.DateField(blank=True, null=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='org.campus')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('investigated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('org_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='org.orgunit')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('what', models.TextField()),
                ('due_on', models.DateField()),
                ('done_on', models.DateField(blank=True, null=True)),
                ('done_note', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='safety_actions', to='people.employee')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='incidents.incident')),
            ],
            options={
                'ordering': ['due_on', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('who', models.CharField(choices=[('staff', 'Member of staff'), ('student', 'Student'), ('contractor', 'Contractor'), ('visitor', 'Visitor')], max_length=12)),
                ('name', models.CharField(blank=True, help_text='Someone not on the staff', max_length=120)),
                ('injury', models.TextField(blank=True, help_text='The injury or illness, and the part of the body')),
                ('treatment', models.CharField(blank=True, choices=[('none', 'None needed'), ('first_aid', 'First aid'), ('doctor', 'Doctor or clinic'), ('hospital', 'Hospital')], max_length=10)),
                ('off_work_from', models.DateField(blank=True, help_text='First day unable to earn full wages', null=True)),
                ('back_at_work_on', models.DateField(blank=True, help_text='First day back on full wages', null=True)),
                ('died_on', models.DateField(blank=True, null=True)),
                ('nis_form_on', models.DateField(blank=True, help_text='When they were given the NIS notice of accident (Form IB1)', null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incident_injuries', to='people.employee')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people', to='incidents.incident')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('duty', models.CharField(choices=[('death', 'A worker killed'), ('disablement', 'A worker kept from full wages for more than a day'), ('later_death', 'A death after the notice of the accident'), ('recovered', 'The day the disablement ended'), ('disease', 'A suspected occupational disease'), ('dangerous', 'A dangerous occurrence')], max_length=12)),
                ('recipient', models.CharField(choices=[('authority', 'The Occupational Safety and Health Authority'), ('workers', 'The safety and health committee, representative or trade union'), ('sanitary', 'The Local Sanitary Authority'), ('medical', 'The medical inspector for the area')], max_length=10)),
                ('sent_on', models.DateField()),
                ('how', models.CharField(help_text='Such as by hand, by email or by registered post', max_length=80)),
                ('their_reference', models.CharField(blank=True, max_length=80)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='incidents.incident')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='incidents.person')),
            ],
            options={
                'ordering': ['sent_on', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('who', 'staff'), ('employee__isnull', False)), models.Q(models.Q(('who', 'staff'), _negated=True), ('employee__isnull', True), models.Q(('name', ''), _negated=True)), _connector='OR'), name='incident_person_named'),
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.UniqueConstraint(fields=('incident', 'employee'), name='incident_staff_once'),
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.CheckConstraint(condition=models.Q(('back_at_work_on__isnull', True), models.Q(('off_work_from__isnull', False), ('back_at_work_on__gt', models.F('off_work_from'))), _connector='OR'), name='incident_back_after_off'),
        ),
        migrations.AddConstraint(
            model_name='notice',
            constraint=models.UniqueConstraint(fields=('incident', 'person', 'duty', 'recipient'), name='incident_notice_once', nulls_distinct=False),
        ),
    ]
