# Generated by Django 5.2.17 on 2026-09-25 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.CharField(help_text='YYYY-MM', max_length=7, unique=True)),
                ('state', models.CharField(choices=[('open', 'Open'), ('locked', 'Locked'), ('exported', 'Exported')], default='open', max_length=10)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('exported_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period'],
            },
        ),
        migrations.CreateModel(
            name='StatutoryRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('nis_employee_pct', 'NIS employee contribution %'), ('nis_employer_pct', 'NIS employer contribution %'), ('nis_ceiling_monthly', 'NIS insurable earnings ceiling (monthly, GYD)'), ('paye_threshold_monthly', 'PAYE tax-free threshold (monthly, GYD)'), ('paye_rate_pct', 'PAYE rate %')], max_length=30)),
                ('value', models.DecimalField(decimal_places=4, max_digits=14)),
                ('effective_from', models.DateField()),
                ('source_reference', models.CharField(blank=True, help_text='Circular or notice reference', max_length=200)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['kind', '-effective_from'],
                'unique_together': {('kind', 'effective_from')},
            },
        ),
    ]
