# Generated by Django 5.2.17 on 2026-10-10 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
        ('people', '0010_scan_batches'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='statutoryrate',
            name='kind',
            field=models.CharField(choices=[('nis_employee_pct', 'NIS employee contribution %'), ('nis_employer_pct', 'NIS employer contribution %'), ('nis_ceiling_monthly', 'NIS insurable earnings ceiling (monthly, GYD)'), ('paye_allowance_monthly', 'PAYE personal allowance, flat (monthly, GYD)'), ('paye_rate_pct', 'PAYE rate, first band %'), ('paye_band2_threshold_monthly', 'PAYE chargeable income where the second band starts (monthly, GYD)'), ('paye_rate_band2_pct', 'PAYE rate, second band %')], max_length=30),
        ),
        migrations.CreateModel(
            name='PayRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.CharField(help_text='YYYY-MM', max_length=7, unique=True)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('calculated', 'Calculated'), ('approved', 'Approved'), ('disbursed', 'Disbursed')], default='draft', max_length=10)),
                ('calculated_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('disbursed_at', models.DateTimeField(blank=True, null=True)),
                ('total_gross', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_nis_employee', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_nis_employer', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_paye', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_net', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period'],
            },
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gross', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unpaid_days', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('unpaid_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('nis_employee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('nis_employer', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('paye', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('breakdown', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='people.document')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payslips', to='people.employee')),
                ('pay_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='payroll.payrun')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['employee'],
                'unique_together': {('pay_run', 'employee')},
            },
        ),
        migrations.DeleteModel(
            name='PayrollPeriod',
        ),
    ]
