# Generated by Django 5.2.17 on 2026-10-02 02:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0009_clearancestep_exitinterview_issueditem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SignatureRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('acknowledge', 'Acknowledge receiving it'), ('accept', 'Accept it')], max_length=12)),
                ('statement', models.CharField(help_text='The sentence they agree to', max_length=300)),
                ('message', models.CharField(blank=True, help_text='A note from HR', max_length=300)),
                ('due_by', models.DateField(blank=True, null=True)),
                ('state', models.CharField(choices=[('waiting', 'Waiting'), ('signed', 'Signed'), ('declined', 'Declined'), ('withdrawn', 'Withdrawn')], default='waiting', max_length=10)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decline_reason', models.CharField(blank=True, max_length=300)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signature_requests', to='people.document')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signature_requests', to='people.employee')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('statement', models.CharField(help_text='As it was shown when they signed', max_length=300)),
                ('document_title', models.CharField(max_length=200)),
                ('document_version', models.PositiveSmallIntegerField()),
                ('sha256', models.CharField(help_text='Fingerprint of the file as it was when signed', max_length=64)),
                ('method', models.CharField(default='password confirmed while signed in', max_length=40)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=200)),
                ('signer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signature', to='signing.signaturerequest')),
            ],
            options={
                'ordering': ['-signed_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='signaturerequest',
            constraint=models.UniqueConstraint(condition=models.Q(('state', 'waiting')), fields=('document', 'employee'), name='one_waiting_request_per_document'),
        ),
    ]
