# Generated by Django 5.2.17 on 2026-10-02 03:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0009_clearancestep_exitinterview_issueditem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(max_length=20, unique=True)),
                ('kind', models.CharField(choices=[('discipline', 'Discipline'), ('grievance', 'Grievance')], max_length=12)),
                ('summary', models.TextField(help_text='The allegation, or the grievance, in words')),
                ('opened_on', models.DateField()),
                ('state', models.CharField(choices=[('open', 'Open'), ('decided', 'Decided'), ('appeal', 'Under appeal'), ('closed', 'Closed')], default='open', max_length=10)),
                ('outcome', models.CharField(blank=True, choices=[('no_action', 'No action'), ('counselling', 'Counselling'), ('verbal_warning', 'Verbal warning'), ('written_warning', 'Written warning'), ('final_warning', 'Final written warning'), ('suspension', 'Suspension'), ('dismissal', 'Dismissal'), ('upheld', 'Grievance upheld'), ('partly_upheld', 'Grievance partly upheld'), ('not_upheld', 'Grievance not upheld'), ('withdrawn', 'Withdrawn')], max_length=20)),
                ('outcome_reasons', models.TextField(blank=True)),
                ('decided_on', models.DateField(blank=True, null=True)),
                ('lapses_on', models.DateField(blank=True, help_text='When a warning stops counting', null=True)),
                ('appeal_lodged_on', models.DateField(blank=True, null=True)),
                ('appeal_grounds', models.TextField(blank=True)),
                ('appeal_outcome', models.CharField(blank=True, choices=[('confirmed', 'Decision confirmed'), ('varied', 'Decision varied'), ('overturned', 'Decision overturned')], max_length=12)),
                ('appeal_reasons', models.TextField(blank=True)),
                ('appeal_decided_on', models.DateField(blank=True, null=True)),
                ('closed_on', models.DateField(blank=True, null=True)),
                ('appeal_decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='people.employee')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-opened_on', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CaseEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('allegation', 'Allegation put in writing'), ('response', 'Response from the employee'), ('investigation', 'Investigation'), ('meeting', 'Meeting'), ('hearing', 'Hearing'), ('note', 'Note')], max_length=20)),
                ('on', models.DateField()),
                ('text', models.TextField()),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='cases.case')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['on', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CaseOfficer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.CharField(help_text='Such as investigating officer, or chair of the hearing', max_length=80)),
                ('named_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='officers', to='cases.case')),
                ('named_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['named_at'],
                'constraints': [models.UniqueConstraint(fields=('case', 'user'), name='named_once_on_a_case')],
            },
        ),
    ]
