# Generated by Django 5.2.17 on 2026-09-25 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=150)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('success', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-at'],
            },
        ),
    ]
