# Generated by Django 5.2.17 on 2026-10-02 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0006_email_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='code',
            field=models.CharField(choices=[('administrator', 'System Administrator'), ('hr_manager', 'HR Manager'), ('hr_officer', 'HR Officer'), ('finance', 'Finance / Payroll Officer'), ('principal', 'Principal / Deputy Principal'), ('supervisor', 'Supervisor / Head of Department'), ('employee', 'Employee'), ('ministry_liaison', 'Ministry of Agriculture Liaison'), ('auditor', 'Auditor'), ('data_protection_officer', 'Data Protection Officer')], max_length=40, unique=True),
        ),
    ]
