# Generated by Django 5.2.17 on 2026-10-10 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0011_onboarding'),
        ('performance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('weight', models.PositiveSmallIntegerField(blank=True, help_text='Out of 100, when goals for the cycle are weighted', null=True)),
                ('status', models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('achieved', 'Achieved'), ('not_achieved', 'Not achieved')], default='not_started', max_length=20)),
                ('position', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['cycle', 'employee', 'position', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='appraisal',
            options={'ordering': ['-cycle__year', 'employee']},
        ),
        migrations.AlterModelOptions(
            name='appraisalcycle',
            options={'ordering': ['-year', 'name']},
        ),
        migrations.AddField(
            model_name='appraisal',
            name='decision_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='manager',
            field=models.ForeignKey(blank=True, help_text="Who rates it: the employee's manager when the appraisal was opened", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='people.employee'),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='manager_assessment',
            field=models.TextField(blank=True, help_text="The manager's assessment and comments"),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='previous_state',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='rated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='self_assessed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='self_assessment',
            field=models.TextField(blank=True, help_text="The employee's own account of the cycle"),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='waiting_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='form_data',
            field=models.JSONField(blank=True, default=dict, help_text='Anything else particular to the form'),
        ),
        migrations.AddConstraint(
            model_name='appraisal',
            constraint=models.CheckConstraint(condition=models.Q(('overall_rating__isnull', True), models.Q(('overall_rating__gte', 1), ('overall_rating__lte', 5)), _connector='OR'), name='appraisal_rating_one_to_five'),
        ),
        migrations.AddField(
            model_name='goal',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='goal',
            name='cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='performance.appraisalcycle'),
        ),
        migrations.AddField(
            model_name='goal',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='people.employee'),
        ),
        migrations.AddField(
            model_name='goal',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='goal',
            constraint=models.CheckConstraint(condition=models.Q(('weight__isnull', True), models.Q(('weight__gte', 0), ('weight__lte', 100)), _connector='OR'), name='goal_weight_nought_to_hundred'),
        ),
    ]
